bookmark/urls.py
from django.urls import path
from bookmark import views
app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkListView.as_view(), name='index'),
    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', views.BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.BookmarkDeleteView.as_view(), name='delete'),
    ]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView, UserCreateView, UserCreateDoneTV



urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls'))

]

polls/urls.py
from django.urls import path
from polls import views
app_name = 'polls'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/result/', views.Result.as_view(), name='result'),
    path('<int:question_id>/reset/', views.reset, name='reset'),


    path('choice_add/', views.ChoiceCV.as_view(), name='choice_add'),


    path('question_add/',views.QuestionCV.as_view(),name='question_add'),

]

bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    site_name = models.CharField('TITLE', max_length=50)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.site_name

polls/models.py
from django.db import models
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

class Kind(models.Model):
    kind_text = models.CharField(max_length=200)

class Information(models.Model):
    question_info = models.ForeignKey(Question, on_delete=models.CASCADE)
    kind_info = models.ForeignKey(Kind, on_delete=models.CASCADE)

polls/forms.py
from django import forms
from django.db import models
from .models import Question, Choice

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['question_id', 'votes', 'choice_text']

bookmark/views.py
from django.views import generic
from .models import Bookmark
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class BookmarkListView(generic.ListView):
    model = Bookmark

class BookmarkCreateView(generic.CreateView):
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('bookmark:index') # url 패턴이름으로 url스트링 구함. 앱이름 꼭 쓰기

class BookmarkDetailView(generic.DetailView):
    model = Bookmark

class BookmarkUpdateView(generic.UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(generic.DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

mysite/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

#--- Homepage
class HomeView(TemplateView):
    template_name = 'home.html'


class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

polls/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from polls.models import Question, Choice, Kind
from django.views import generic
from django.urls import reverse_lazy
from .forms import ChoiceForm, QuestionForm
# Create your views here.
# def index(request):
#     latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
#     return render(request, 'polls/index.html', {'latest_question_list': latest_question_list})

class QuestionCV(generic.CreateView):
    model = Question
    template_name = 'polls/question_create.html'
    success_url = reverse_lazy('polls:index')
    fields = ['question_text']
    #form_class = QuestionForm



class ChoiceCV(generic.CreateView):
    template_name = 'polls/choice_create.html'
    success_url = reverse_lazy('polls:index')
    form_class = ChoiceForm

class IndexView(generic.ListView):
    model = Question
    context_object_name = 'new_list'
    template_name = 'polls/index.html'

    def get_queryset(self):
        return Question.objects.all().order_by('-pub_date')[:3]

#def index(request):
#    latest_question_list = Question.objects.all().order_by('-pub_date')[:3]
#    context = {'latest_question_list': latest_question_list}
#    return render(request, 'polls/index.html', context)


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})


class DetailView(generic.DetailView):
    model = Question
    context_object_name = 'question'
    template_name = 'polls/detail.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['select'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice"
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:result', args=(question.id,)))

# def result(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/result.html', {'question': question})

class Result(generic.DetailView):
    model = Question
    context_object_name = 'question'
    template_name = 'polls/result.html'





def reset(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    reset_list = question.choice_set.all()
    for i in reset_list:
        i.votes = 0
        i.save()
    return HttpResponseRedirect(reverse('polls:result', args=(question_id,)))

# class Reset(generic.View):
#     model = Question
#     def cal(self, request, pk):
#         question = get_object_or_404(Question, pk=pk)
#         reset_list = question.choice_set.all()
#         for i in reset_list:
#             i.votes = 0
#             i.save()
#         return HttpResponseRedirect(reverse('polls:result', args=(pk,)))

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %} 북마크 생성 및 수정 {% endblock %}
{% block content %}
<body>
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">
        {{ object }} <br>
        정말로 삭제 하시겠습니까?
    </div>
    <input type="submit" value="Delete" class="btn btn-danger">
</form>
</body>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post" autocomplete="off"> <!-- 이전에 브라우저가 입력한 것 기억하여 자동완성 하는기능 -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>

</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %} 북마크 상세정보 {% endblock %}
{% block content %}
<body>
{{ object.site_name }} <br>
{{ object.url }}
</body>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends 'bookmark/layout.html' %}
{% block title %} 북마크 생성 및 수정 {% endblock %}
{% block content %}
<h1>Create or Update</h1>
<form action="" method="post" autocomplete="off"> <!-- 이전에 브라우저가 입력한 것 기억하여 자동완성 하는기능 -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add or Change" class="btn btn-info btn-sm">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block content %}
<body>
<div>
    <h1><a href="{% url 'bookmark:add' %}" class="btn-info btn-sm">Add Bookmark</a></h1>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">No</th>
        <th scope="col">Site</th>
        <th scope="col">URL</th>
        <th scope="col">Modify</th>
        <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for bookmark in object_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark.site_name }}</a></td>
        <td><a href="{{ bookmark.url }}">{{ bookmark.url }}</a> </td>
        <td><a href="{% url 'bookmark:update' bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
        <td><a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-danger btn-sm">delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

</body>
{% endblock %}

bookmark/templates/bookmark/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Bookmark</a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
    </ul>

</nav>
{% block content %}

{% endblock %}
</body>
</html>

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'polls:index' %}">Polls</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a></li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>

            </li>
        </ul>

        <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
        </form>

        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
            	    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                <div class="dropdown-menu">
            	    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            	    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
            	    <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                <div class="dropdown-menu">
            	    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            	    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>


{% block footer %}{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Bookmark is a Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of various storage formats.
                You can store your own bookmarks by Bookmark application.
                It's also possible to update or delete your bookmarks.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2020 DjangoBook by lwb</div>
</footer>
{% endblock %}

polls/templates/polls/choice_create.html
{% extends 'base.html' %}
{% block title %} 북마크 생성 및 수정 {% endblock %}
{% block content %}
<h1>Create or Update</h1>
<form action="" method="post" autocomplete="off"> <!-- 이전에 브라우저가 입력한 것 기억하여 자동완성 하는기능 -->
    {% csrf_token %}
    <div class="form-group">
    {{ form.as_p }}
    </div>
    <input type="submit" value="Add or Change" class="btn btn-info btn-sm">

</form>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block title %} 북마크 생성 및 수정 {% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
<ul>
    {% for choice in question.choice_set.all %}
    <input type="radio" id="choice{{ forloop.count }}" name="select" value="{{ choice.id }}">
    <lable for="choice{{ forloop.counter }}">{{ choice.choice_text }}</lable><br>
    {% endfor %}
</ul>
    <input type="submit" value="vote">
    <a href="{% url 'polls:choice_add' %}">choice_add</a>

</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}
{% block title %}
설문조사 리스트
{% endblock %}

{% block content %}
{% if new_list %}
<div class="row row-cols-1 row-cols-md-3">
{% for question in new_list %}
<div class="col mb-4">
<div class="card h-100">
  <div class="card-body">
    <h5 class="card-title">{{ question.question_text }}</h5>
    <p class="card-text">{{ question.pub_date }}</p>
    <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary">Go vote!</a>
  </div>
</div>
</div>
{% endfor %}
</div>
{% else %}
<p>No Questions</p>
{% endif %}
<button type="button" class="btn btn-primary btn-lg btn-block" onclick="location.href='{% url 'polls:question_add' %}'">Add Question</button>
{% endblock %}

polls/templates/polls/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mysite/style.css' %}"/>

</head>
<body>
<h1>MySite</h1>
{% block content %}
<div id="content">
    <a href="{% url 'polls:index' %}" >
        <div>polls app</div>
    </a>
        <div>bookmark app</div>
        <div>books</div>
</div>
{% endblock %}
<footer>
    <div class="info">
        인천과학예술영재학교<br>
        주소: 인천광역시 연수구 송도2동 아카데미로 192<br>
        연락처: 032-890-6700<br>
        교직원 수: 62명 (2018년 5월 1일 기준)<br>
        학생 수: 230명 (2018년 5월 1일 기준)<br>
    </div>

    <div class="info">
        이름: 홍길동<br>
        학번: 20312<br>
        홈페이지 소개<br>
    </div>
</footer>
</body>
</html>

polls/templates/polls/question_create.html
{% extends 'base.html' %}
{% block title %} 북마크 생성 및 수정 {% endblock %}
{% block content %}
<h1>Create or Update</h1>
<form action="" method="post" autocomplete="off"> <!-- 이전에 브라우저가 입력한 것 기억하여 자동완성 하는기능 -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add or Change" class="btn btn-info btn-sm">
</form>
{% endblock %}

polls/templates/polls/result.html
{% extends 'base.html' %}
{% block title %} 북마크 생성 및 수정 {% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:index' %}">Index</a>
<a href="{% url 'polls:reset' question.id %}">Reset</a>

{% endblock %}